from __future__ import annotations

import hashlib
import re
import time
import unicodedata
from typing import Any, Mapping, Sequence
from uuid import uuid4

from agentic_rl.outcome.parser import parse_model_action, parse_model_trajectory
from agentic_rl.exact_ig.target_schema import select_canonical_answer
from agentic_rl.retriever.client import AsyncHybridRetrieverClient
from agentic_rl.retriever.protocol import RetrievalDocument
from agentic_rl.rollout.trajectory_schema import TokenSource, TurnType
from agentic_rl.rollout.search_role_provenance import (
    ROLE_LOCALIZED_BRANCH_N_BUDGET,
    ROLE_LOCALIZED_BRANCH_N_INVALID,
    ROLE_LOCALIZED_BRANCH_N_SOFT,
    ROLE_LOCALIZED_BRANCH_NORMAL,
    action_has_search_intent,
    build_invalid_search_role_spans,
    build_generation_time_search_role_spans,
    exact_search_payload_text,
)

from verl.experimental.agent_loop.agent_loop import (
    AgentLoopBase,
    AgentLoopMetrics,
    AgentLoopOutput,
)


def normalize_passage_text(value: str) -> str:
    """Normalize complete passage text only for the SHA-256 fallback key."""

    normalized = unicodedata.normalize("NFKC", str(value))
    return re.sub(r"\s+", " ", normalized).strip()


def stable_passage_key(document: RetrievalDocument) -> str:
    passage_id = str(document.passage_id).strip()
    if passage_id:
        return f"passage_id:{passage_id}"
    normalized = normalize_passage_text(document.contents)
    if not normalized:
        raise ValueError("A passage without an ID must have non-empty full text")
    digest = hashlib.sha256(normalized.encode("utf-8")).hexdigest()
    return f"text_sha256:{digest}"


def normalize_query_for_exact_repeat(value: str) -> str:
    normalized = unicodedata.normalize("NFKC", str(value)).strip()
    collapsed = re.sub(r"\s+", " ", normalized)
    return collapsed.casefold()


def compute_and_commit_passage_novelty(
    seen_passage_keys: set[str],
    documents: Sequence[RetrievalDocument],
) -> tuple[set[str], set[str], bool]:
    """Compute N against the pre-Search set, then commit current passages."""

    current_passage_keys = {stable_passage_key(document) for document in documents}
    new_passage_keys = current_passage_keys - seen_passage_keys
    no_new_observation = not new_passage_keys
    seen_passage_keys.update(current_passage_keys)
    return current_passage_keys, new_passage_keys, no_new_observation


def _as_messages(value: Any) -> list[dict[str, str]]:
    if hasattr(value, "tolist"):
        value = value.tolist()
    if not isinstance(value, Sequence) or isinstance(value, (str, bytes)):
        raise ValueError("raw_prompt must be a message sequence")
    messages: list[dict[str, str]] = []
    for item in value:
        if not isinstance(item, Mapping):
            raise ValueError("raw_prompt entries must be mappings")
        role = str(item.get("role", "")).strip()
        content = str(item.get("content", ""))
        if not role or not content:
            raise ValueError("raw_prompt messages require role and content")
        messages.append({"role": role, "content": content})
    return messages


def _as_aliases(value: Any) -> tuple[str, ...]:
    if hasattr(value, "tolist"):
        value = value.tolist()
    if isinstance(value, str):
        values = (value,)
    elif isinstance(value, Sequence):
        values = tuple(value)
    else:
        raise ValueError("gold_aliases must be a string sequence")
    aliases = tuple(str(item) for item in values if str(item).strip())
    if not aliases:
        raise ValueError("gold_aliases cannot be empty")
    return aliases


class SearchExactIGAgentLoop(AgentLoopBase):
    """Multi-turn Search-R1 loop with explicit token provenance.

    Each model action is generated by one sticky vLLM request. Retriever and
    code-inserted tokens are recorded with response mask zero. A malformed
    model action is a real model-generated terminal fallback; no synthetic
    Answer turn is created when the model never emits a terminal span.
    """

    @classmethod
    def init_class(
        cls,
        config: Any,
        tokenizer: Any,
        processor: Any,
        **kwargs: Any,
    ) -> None:
        if cls._class_initialized:
            return
        cls._class_initialized = True
        cls.tokenizer = tokenizer
        cls.processor = processor
        cls.prompt_length = int(config.actor_rollout_ref.rollout.prompt_length)
        cls.response_length = int(config.actor_rollout_ref.rollout.response_length)
        cls.apply_chat_template_kwargs = config.data.get(
            "apply_chat_template_kwargs",
            {},
        )
        cls.max_search_turns = int(kwargs["max_search_turns"])
        cls.max_new_tokens_per_turn = int(kwargs["max_new_tokens_per_turn"])
        cls.max_information_tokens_per_turn = int(
            kwargs["max_information_tokens_per_turn"]
        )
        cls.sampling_top_k = int(kwargs.get("sampling_top_k", 0))
        cls.sampling_min_p = float(kwargs.get("sampling_min_p", 0.0))
        cls.repetition_penalty = float(
            kwargs.get("repetition_penalty", 1.0)
        )
        cls.presence_penalty = float(kwargs.get("presence_penalty", 0.0))
        cls.frequency_penalty = float(kwargs.get("frequency_penalty", 0.0))
        cls.role_localized_gate_enabled = bool(
            kwargs.get("role_localized_gate_enabled", False)
        )
        cls.retriever = AsyncHybridRetrieverClient(
            str(kwargs["retriever_url"]),
            timeout_seconds=float(kwargs["retriever_request_timeout_seconds"]),
            maximum_concurrency=int(kwargs["retriever_max_concurrency"]),
            batch_wait_ms=float(kwargs["retriever_batch_window_ms"]),
        )

    async def _initial_prompt_ids(self, messages: Sequence[dict[str, str]]) -> list[int]:
        return await self.loop.run_in_executor(
            None,
            lambda: self.tokenizer.apply_chat_template(
                list(messages),
                add_generation_prompt=True,
                tokenize=True,
                **self.apply_chat_template_kwargs,
            ),
        )

    def _information_token_ids(
        self,
        documents: Sequence[RetrievalDocument],
    ) -> tuple[list[int], str]:
        body = "\n".join(document.contents for document in documents)
        prefix = self.tokenizer(
            "<information>",
            add_special_tokens=False,
            return_attention_mask=False,
        )["input_ids"]
        suffix = self.tokenizer(
            "</information>",
            add_special_tokens=False,
            return_attention_mask=False,
        )["input_ids"]
        budget = self.max_information_tokens_per_turn - len(prefix) - len(suffix)
        if budget < 0:
            raise RuntimeError("Information-token cap is smaller than protocol tags")
        body_ids = self.tokenizer(
            body,
            add_special_tokens=False,
            return_attention_mask=False,
        )["input_ids"][:budget]
        token_ids = [int(value) for value in (*prefix, *body_ids, *suffix)]
        rendered = self.tokenizer.decode(token_ids, skip_special_tokens=False)
        return token_ids, rendered

    async def run(
        self,
        sampling_params: dict[str, Any],
        **kwargs: Any,
    ) -> AgentLoopOutput:
        started = time.perf_counter()
        messages = _as_messages(kwargs["raw_prompt"])
        aliases = _as_aliases(kwargs["gold_aliases"])
        canonical_answer = select_canonical_answer(kwargs["canonical_answer"])
        prompt_global_id = str(kwargs["prompt_global_id"])
        trajectory_id = str(
            kwargs.get("trajectory_id")
            or f"{prompt_global_id}:{uuid4().hex}"
        )
        snapshot_step = int(kwargs["snapshot_step"])
        data_source = str(kwargs.get("data_source", ""))
        dataset_row_id = str(kwargs.get("dataset_row_id", ""))
        dataset_source_index = int(kwargs.get("dataset_source_index", -1))
        request_id = f"{trajectory_id}:snapshot-{snapshot_step}"
        prompt_ids = await self._initial_prompt_ids(messages)
        if not prompt_ids or len(prompt_ids) > self.prompt_length:
            raise RuntimeError("Prompt is empty or exceeds configured prompt_length")

        response_ids: list[int] = []
        response_mask: list[int] = []
        response_logprobs: list[float] = []
        response_sources: list[str] = []
        response_turn_ids: list[int] = []
        model_actions: list[str] = []
        search_queries: list[str] = []
        retrieval_records: list[dict[str, Any]] = []
        turn_records: list[dict[str, Any]] = []
        # Prefix zero is the complete prompt before any Search.
        prefix_end_positions: list[int] = [len(prompt_ids)]
        prefix_before_search_end_positions: dict[int, int] = {}
        termination_reason = "no_terminal_model_span"
        system_valid = True
        environment_failure_code: str | None = None
        search_count = 0
        seen_passage_keys: set[str] = set()
        seen_normalized_queries: set[str] = set()

        for turn_index in range(self.max_search_turns + 1):
            remaining_response = self.response_length - len(response_ids)
            if remaining_response <= 0:
                termination_reason = "response_length_exhausted"
                break
            pre_action_prefix_end = len(prompt_ids) + len(response_ids)
            params = dict(sampling_params)
            params["top_k"] = (
                -1 if self.sampling_top_k == 0 else self.sampling_top_k
            )
            params["min_p"] = self.sampling_min_p
            params["repetition_penalty"] = self.repetition_penalty
            params["presence_penalty"] = self.presence_penalty
            params["frequency_penalty"] = self.frequency_penalty
            params["project_max_tokens"] = min(
                self.max_new_tokens_per_turn,
                remaining_response,
            )
            generated_started = time.perf_counter()
            output = await self.server_manager.generate(
                request_id=request_id,
                prompt_ids=prompt_ids + response_ids,
                sampling_params=params,
                image_data=None,
            )
            generated_seconds = time.perf_counter() - generated_started
            action_ids = [int(value) for value in output.token_ids]
            if not action_ids:
                termination_reason = "empty_model_fallback"
                break
            action_text = self.tokenizer.decode(
                action_ids,
                skip_special_tokens=True,
                clean_up_tokenization_spaces=False,
            )
            model_actions.append(action_text)
            response_ids.extend(action_ids)
            response_mask.extend([1] * len(action_ids))
            response_sources.extend([TokenSource.MODEL.value] * len(action_ids))
            response_turn_ids.extend([turn_index] * len(action_ids))
            if output.log_probs is None:
                response_logprobs.extend([0.0] * len(action_ids))
            else:
                if len(output.log_probs) != len(action_ids):
                    raise RuntimeError("vLLM token/logprob cardinality mismatch")
                response_logprobs.extend(float(value) for value in output.log_probs)

            parsed = parse_model_action(action_text, action_index=turn_index)
            role_spans = None
            raw_query_payload: str | None = None
            role_protocol_error: str | None = None
            role_provenance_fallback = False
            if self.role_localized_gate_enabled and (
                parsed.kind == "search" or action_has_search_intent(action_text)
            ):
                try:
                    role_spans = build_generation_time_search_role_spans(
                        self.tokenizer,
                        action_token_ids=action_ids,
                        action_text=action_text,
                        absolute_action_start=pre_action_prefix_end,
                        allow_incomplete_search=True,
                    )
                except ValueError as error:
                    if parsed.valid:
                        raise
                    role_spans = build_invalid_search_role_spans(
                        self.tokenizer,
                        action_token_ids=action_ids,
                        action_text=action_text,
                        absolute_action_start=pre_action_prefix_end,
                    )
                    role_provenance_fallback = True
                    role_protocol_error = (
                        f"invalid_search_role_provenance:{type(error).__name__}:"
                        f"{error}"
                    )
                raw_query_payload = exact_search_payload_text(
                    action_text,
                    allow_incomplete_search=(
                        not parsed.valid or role_provenance_fallback
                    ),
                )
                if role_spans.think is None:
                    role_protocol_error = "invalid_think_structure"
            if not parsed.valid or role_protocol_error is not None:
                if self.role_localized_gate_enabled and role_spans is not None:
                    model_search_error = (
                        role_protocol_error
                        or parsed.error
                        or "invalid_model_search"
                    )
                    search_index = search_count
                    search_count += 1
                    prefix_before_search_end_positions[search_index] = int(
                        pre_action_prefix_end
                    )
                    raw_query = str(raw_query_payload or "")
                    canonical_query = normalize_query_for_exact_repeat(raw_query)
                    exact_query_repeat = bool(
                        canonical_query
                        and canonical_query in seen_normalized_queries
                    )
                    if canonical_query:
                        seen_normalized_queries.add(canonical_query)
                    search_queries.append(raw_query.strip())
                    stable_keys = sorted(seen_passage_keys)
                    turn_records.append(
                        {
                            "turn_index": turn_index,
                            "turn_type": TurnType.SEARCH.value,
                            "model_text": action_text,
                            "search_index": search_index,
                            "prefix_before_search_end_position": int(
                                pre_action_prefix_end
                            ),
                            "query": raw_query.strip() or None,
                            "information_text": None,
                            "parser_status": "invalid",
                            "parser_error_type": model_search_error,
                            "search_action_span_valid": False,
                            "search_prefix_valid": False,
                            "ig_reward_eligible": False,
                            "policy_credit_eligible": True,
                            "no_new_observation": None,
                            "exact_query_repeat": exact_query_repeat,
                            "different_query_no_new_passage": False,
                            "current_passage_keys": [],
                            "new_passage_keys": [],
                            "role_localized_gate_enabled": True,
                            "retriever_executed": False,
                            "retrieval_budget_exhausted": False,
                            "model_search_invalid": True,
                            "main_credit_eligible": False,
                            "branch_type": ROLE_LOCALIZED_BRANCH_N_INVALID,
                            "no_new_reason": str(model_search_error),
                            "raw_query": raw_query,
                            "canonical_query": canonical_query,
                            "new_passage_count": 0,
                            "stable_passage_keys_before": stable_keys,
                            "stable_passage_keys_after": stable_keys,
                            **role_spans.as_dict(),
                            "observation_token_span": None,
                            "generation_seconds": generated_seconds,
                        }
                    )
                    termination_reason = "model_generated_malformed_search"
                    break
                turn_records.append(
                    {
                        "turn_index": turn_index,
                        "turn_type": TurnType.FALLBACK.value,
                        "model_text": action_text,
                        "search_index": None,
                        "query": None,
                        "information_text": None,
                        "parser_status": "invalid",
                        "parser_error_type": parsed.error,
                        "search_action_span_valid": False,
                        "search_prefix_valid": False,
                        "ig_reward_eligible": False,
                        "policy_credit_eligible": True,
                        "generation_seconds": generated_seconds,
                    }
                )
                termination_reason = "model_generated_malformed_fallback"
                break
            if parsed.kind == "answer":
                turn_records.append(
                    {
                        "turn_index": turn_index,
                        "turn_type": TurnType.ANSWER.value,
                        "model_text": action_text,
                        "search_index": None,
                        "query": None,
                        "information_text": None,
                        "parser_status": "valid",
                        "parser_error_type": None,
                        "search_action_span_valid": False,
                        "search_prefix_valid": False,
                        "ig_reward_eligible": False,
                        "policy_credit_eligible": True,
                        "generation_seconds": generated_seconds,
                    }
                )
                termination_reason = "model_answer"
                break

            query = str(parsed.value)
            normalized_query = normalize_query_for_exact_repeat(query)
            if self.role_localized_gate_enabled and role_spans is None:
                raise RuntimeError("Valid Search is missing generation-time role spans")
            exact_query_repeat = normalized_query in seen_normalized_queries
            seen_normalized_queries.add(normalized_query)
            search_index = search_count
            search_count += 1
            prefix_before_search_end_positions[search_index] = int(
                pre_action_prefix_end
            )
            search_queries.append(query)
            if search_count > self.max_search_turns:
                turn_records.append(
                    {
                        "turn_index": turn_index,
                        "turn_type": TurnType.SEARCH.value,
                        "model_text": action_text,
                        "search_index": search_index,
                        "prefix_before_search_end_position": int(
                            pre_action_prefix_end
                        ),
                        "query": query,
                        "information_text": None,
                        "parser_status": "valid",
                        "parser_error_type": None,
                        "search_action_span_valid": True,
                        "search_prefix_valid": False,
                        "ig_reward_eligible": False,
                        "policy_credit_eligible": True,
                        "no_new_observation": True,
                        "exact_query_repeat": exact_query_repeat,
                        "different_query_no_new_passage": not exact_query_repeat,
                        "current_passage_keys": [],
                        "new_passage_keys": [],
                        **(
                            {
                                "role_localized_gate_enabled": True,
                                "retriever_executed": False,
                                "retrieval_budget_exhausted": True,
                                "model_search_invalid": False,
                                "main_credit_eligible": False,
                                "branch_type": ROLE_LOCALIZED_BRANCH_N_BUDGET,
                                "no_new_reason": "retrieval_budget_exhausted",
                                "raw_query": str(raw_query_payload),
                                "canonical_query": normalized_query,
                                "new_passage_count": 0,
                                "stable_passage_keys_before": sorted(
                                    seen_passage_keys
                                ),
                                "stable_passage_keys_after": sorted(
                                    seen_passage_keys
                                ),
                                **role_spans.as_dict(),
                                "observation_token_span": None,
                            }
                            if self.role_localized_gate_enabled
                            else {}
                        ),
                        "generation_seconds": generated_seconds,
                    }
                )
                termination_reason = "maximum_search_turns_reached"
                break

            stable_passage_keys_before = tuple(sorted(seen_passage_keys))
            try:
                retrieval = await self.retriever.retrieve_one(
                    query,
                    trajectory_id,
                    turn_index,
                )
                information_ids, information_text = self._information_token_ids(
                    retrieval.documents
                )
                (
                    current_passage_keys,
                    new_passage_keys,
                    no_new_observation,
                ) = compute_and_commit_passage_novelty(
                    seen_passage_keys,
                    retrieval.documents,
                )
                if len(response_ids) + len(information_ids) > self.response_length:
                    raise RuntimeError("retriever_information_exceeds_response_budget")
            except BaseException as exc:
                system_valid = False
                environment_failure_code = type(exc).__name__
                turn_records.append(
                    {
                        "turn_index": turn_index,
                        "turn_type": TurnType.SEARCH.value,
                        "model_text": action_text,
                        "search_index": search_index,
                        "prefix_before_search_end_position": int(
                            pre_action_prefix_end
                        ),
                        "query": query,
                        "information_text": None,
                        "parser_status": "valid",
                        "parser_error_type": None,
                        "search_action_span_valid": True,
                        "search_prefix_valid": False,
                        "ig_reward_eligible": False,
                        "policy_credit_eligible": False,
                        "generation_seconds": generated_seconds,
                    }
                )
                termination_reason = "retriever_system_failure"
                break

            observation_start = len(prompt_ids) + len(response_ids)
            response_ids.extend(information_ids)
            response_mask.extend([0] * len(information_ids))
            response_logprobs.extend([0.0] * len(information_ids))
            response_sources.extend(
                [TokenSource.ENVIRONMENT.value] * len(information_ids)
            )
            response_turn_ids.extend([-1] * len(information_ids))
            observation_end = len(prompt_ids) + len(response_ids)
            prefix_end_positions.append(observation_end)
            retrieval_records.append(
                {
                    "request_id": retrieval.request_id,
                    "turn_id": turn_index,
                    "query": query,
                    "latency_seconds": retrieval.latency_seconds,
                    "batch_query_count": retrieval.batch_query_count,
                    "document_ids": [
                        document.document_id for document in retrieval.documents
                    ],
                    "document_scores": [
                        document.score for document in retrieval.documents
                    ],
                    "information_token_ids": information_ids,
                    "current_passage_keys": sorted(current_passage_keys),
                    "new_passage_keys": sorted(new_passage_keys),
                    "no_new_observation": bool(no_new_observation),
                    "exact_query_repeat": bool(exact_query_repeat),
                    "different_query_no_new_passage": bool(
                        no_new_observation and not exact_query_repeat
                    ),
                }
            )
            turn_records.append(
                {
                    "turn_index": turn_index,
                    "turn_type": TurnType.SEARCH.value,
                    "model_text": action_text,
                    "search_index": search_index,
                    "prefix_before_search_end_position": int(
                        pre_action_prefix_end
                    ),
                    "query": query,
                    "information_text": information_text,
                    "parser_status": "valid",
                    "parser_error_type": None,
                    "search_action_span_valid": True,
                    "search_prefix_valid": True,
                    "ig_reward_eligible": True,
                    "policy_credit_eligible": True,
                    "no_new_observation": bool(no_new_observation),
                    "exact_query_repeat": bool(exact_query_repeat),
                    "different_query_no_new_passage": bool(
                        no_new_observation and not exact_query_repeat
                    ),
                    "current_passage_keys": sorted(current_passage_keys),
                    "new_passage_keys": sorted(new_passage_keys),
                    **(
                        {
                            "role_localized_gate_enabled": True,
                            "retriever_executed": True,
                            "retrieval_budget_exhausted": False,
                            "model_search_invalid": False,
                            "main_credit_eligible": True,
                            "branch_type": (
                                ROLE_LOCALIZED_BRANCH_N_SOFT
                                if no_new_observation
                                else ROLE_LOCALIZED_BRANCH_NORMAL
                            ),
                            "no_new_reason": (
                                "empty_retrieval"
                                if not retrieval.documents
                                else "no_new_stable_passage"
                                if no_new_observation
                                else None
                            ),
                            "raw_query": str(raw_query_payload),
                            "canonical_query": normalized_query,
                            "new_passage_count": len(new_passage_keys),
                            "stable_passage_keys_before": list(
                                stable_passage_keys_before
                            ),
                            "stable_passage_keys_after": sorted(
                                seen_passage_keys
                            ),
                            **role_spans.as_dict(),
                            "observation_token_span": [
                                observation_start,
                                observation_end,
                            ],
                        }
                        if self.role_localized_gate_enabled
                        else {}
                    ),
                    "generation_seconds": generated_seconds,
                }
            )

        parsed_trajectory = parse_model_trajectory(model_actions)
        if not system_valid:
            for turn in turn_records:
                turn["policy_credit_eligible"] = False
                turn["ig_reward_eligible"] = False

        metrics = AgentLoopMetrics(
            generate_sequences=time.perf_counter() - started,
            tool_calls=sum(
                float(record["latency_seconds"]) for record in retrieval_records
            ),
        )
        full_sources = (
            [TokenSource.PROMPT.value] * len(prompt_ids) + response_sources
        )
        full_turn_ids = [-1] * len(prompt_ids) + response_turn_ids
        extra_fields = {
            "prompt_global_id": prompt_global_id,
            "trajectory_id": trajectory_id,
            "snapshot_step": snapshot_step,
            "data_source": data_source,
            "dataset_row_id": dataset_row_id,
            "dataset_source_index": dataset_source_index,
            "gold_aliases": aliases,
            "canonical_answer": canonical_answer,
            "full_input_ids_unpadded": prompt_ids + response_ids,
            "token_sources_unpadded": full_sources,
            "turn_ids_unpadded": full_turn_ids,
            "sampled_action_logprobs_unpadded": (
                [0.0] * len(prompt_ids) + response_logprobs
            ),
            "prefix_end_positions": prefix_end_positions,
            "prefix_before_search_end_positions": (
                prefix_before_search_end_positions
            ),
            "model_actions": model_actions,
            "search_queries": search_queries,
            "turn_records": turn_records,
            "retrieval_records": retrieval_records,
            "termination_reason": termination_reason,
            "trajectory_system_valid": system_valid,
            "environment_failure_code": environment_failure_code,
            "parser_status": parsed_trajectory.parser_status,
            "parser_error_type": parsed_trajectory.parser_error_type,
            "terminal_answer_valid": parsed_trajectory.terminal_answer_valid,
            "trajectory_protocol_valid": parsed_trajectory.trajectory_valid,
            "answer_format_indicator": parsed_trajectory.answer_format_indicator,
            "fallback_status": parsed_trajectory.fallback_status,
        }
        return AgentLoopOutput(
            prompt_ids=prompt_ids,
            response_ids=response_ids,
            response_mask=response_mask,
            response_logprobs=response_logprobs,
            multi_modal_data={},
            # veRL's disabled-RM path otherwise invokes its generic reward
            # router. This transport-only zero is ignored by the strict runtime;
            # project Outcome/Exact-IG are computed from extra_fields.
            reward_score=0.0,
            num_turns=len(turn_records) + 1,
            metrics=metrics,
            extra_fields=extra_fields,
        )
